version: '3.8'

services:
  app:
    image: python:3.12
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/sh -c "pip install -r requirements.txt && python run.py"
    ports:
      - "5005:5000"